### ISSUE TITLE
Error when i launch the command cli using routing ts template

### ISSUE THREAD

**Issue by lims-team** [pxblue/react-native-cli-templates#139]
warn Ignoring custom template: 'react-native-template-typescript'. Starting from React Native v0.71 TypeScript is used by default.
- Downloading template
✔ Downloading template
- Copying template
✖ Copying template
error Couldn't find the "/var/folders/n4/vk2690gd4l5f1sfxng_xdqdm0000gn/T/rncli-init-template-LX9ovi/node_modules/react-native/template.config.js file inside "react-native" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template.

**Comment by ektaghag-eaton** [comment]
With newest version of templates we need to use RN CLI instead of BLUI CLI. Please refer https://github.com/etn-ccis/blui-react-native-cli-templates/blob/dev/README.md#usage `npx react-native init MyApp --template @brightlayer-ui/react-native-template-routing-typescript` for creating template.
