### ISSUE TITLE
Routing template missing drawer navigation in new project

### ISSUE THREAD

**Issue by jeffvg** [pxblue/react-native-cli-templates#38]
#### Describe the bug
On a new RN routing project spun up via latest "npx -p @pxblue/cli" has missing drawer navigation / icon

![image](https://user-images.githubusercontent.com/37150565/135906930-45576b58-0233-4b15-b4ba-597c5a00432c.png)

#### What is the expected behavior?
Drawer nav to be available and navs to page 1 & 2
#### What are the steps to reproduce?
1. open new terminal and run npx -p @pxblue/cli > react-native > routing
2. cd ios > pod install
3. run android/ios

**Comment by jeffvg** [comment]
verified this after we updated to use react-native 64 and this is still an issue. Tested with cli 1.8.1-beta.0

**Comment by daileytj** [comment]
> verified this after we updated to use react-native 64 and this is still an issue. Tested with cli 1.8.1-beta.0

Looks like this may be an issue with icons in general as the icons for empty state and the change password bottom sheet aren't showing. Some of the drawer icons are showing, but perhaps those are from a different package than the others. I haven't dug into it yet, but that's what it looks like at first glance.
